export const STATEMENTS = {
    ALL: 'all',
    DELETE_FROM: 'deleteFrom',
    FROM : 'from',
    INSERT_INTO: 'insertInto',
    RETURNING: 'returning',
    SET : 'set',
    SELECT: 'select',
    UPDATE: 'update',
    VALUES: 'values',
    WHERE: 'where',
    AND: 'and',
    AS: 'as',
    EQUAL: 'equal',
    UNEQUAL: 'unequal',
    OR: 'or',
    IN: 'in',
    ANY: 'any',
    GT: 'gt',
    GTE: 'gte',
    LT: 'lt',
    LTE: 'lte',
    LIMIT: 'limit',
    OFFSET: 'offset',
    MATCH: 'match',
    MATCHI: 'matchi',
    IS: 'is',
    NOT: 'not',
    NULL: 'null',
}

export const STATEMENT_MAPPING = {
    select: null,
    from : null,
    where : null,
    update: null ,
    SET: null,
    insertInto: null ,
    values: null,
    deleteFrom: null
}